// Матнҳо аз values/strings.xml (тоҷикӣ)
export const t = {
  appName: 'ZabonDon',
  loading: 'Бор шуда истодааст…',
  loadError: 'Пайвастшавӣ ба база ғалат шуд',
  retry: 'Аз нав кӯшиш кунед',
  levelLabel: (n: number) => `САТҲИ ${n}`,
  levelTitle: ['', 'Оғоз', 'Ҳаёти ҳаррӯза', 'Вазъиятҳои амалӣ', 'Муҳоҷират ва кор', 'Пешрафта'],
  levelSub: ['', 'Ашёи мушаххас ва дидашаванда', 'Хона, хӯрок, нақлёт ва шаҳр', 'Харид, вақт, духтур ва фурудгоҳ', 'Сарҳад, стройка ва касбҳо', 'Калимаҳои абстрактӣ ва нодир'],
  wordsCount: (n: number) => `${n} калима`,
  premiumLocked: 'Ин категория барои Premium аст',
  premiumLockedSub: 'Бо Premium ҳамаи категорияҳо кушода мешаванд',
  notFound: 'Чизе ёфт нашуд',
  searchWords: 'Ҷустуҷӯи калима ё категория…',
  catalog: 'Каталог',
  noWords: 'Дар ин категория калима нест',
  statusKnown: 'Омӯхта шуд',
  statusRepeat: 'Дар омӯзиш',
  langRu: 'Русӣ',
  langTj: 'Тоҷикӣ',
  example: 'Мисол',
  finishTitle: 'Дарс анҷом ёфт!',
  finishKnown: 'Омӯхта шуд',
  mistakes: 'Хатогиҳо',
  next: 'Давом',
  know: 'Медонам',
  dontKnow: 'Омӯзиш',
  queueLabel: 'Ба омӯзиш',
  alreadyKnown: 'Медонистам',
  masteredStat: 'Аз худ шуд',
  startGames: 'Оғози бозиҳо',
  phaseIntro: 'Шиносӣ',
  phaseGames: 'Бозиҳо',
  masteredLabel: 'Аз худ шуд',
  pickTjPrompt: 'Тарҷумаро интихоб кунед',
  pickRuPrompt: 'Калимаи русиро интихоб кунед',
  typePrompt: 'Калимаро ба русӣ нависед',
  typePlaceholder: 'Ба русӣ нависед…',
  matchPrompt: 'Ҷуфтҳоро пайваст кунед',
  clozePrompt: 'Ҷойи холиро пур кунед',
  scramblePrompt: 'Калимаро аз ҳарфҳо ҷамъ кунед',
  check: 'Санҷидан',
  correct: 'Дуруст!',
  wrong: 'Нодуруст',
  rightAnswer: 'Ҷавоби дуруст:',
  roundDone: (n: number) => `${n} калима аз худ шуд!`,
  nextRound: 'Калимаҳои навбатӣ',
  finishCoins: 'Тангаҳо',
  backHome: 'Ба саҳифаи асосӣ',
  allDone: 'Ҳамаи калимаҳои намунавӣ омӯхта шуданд',
  resetProgress: 'Аз нав оғоз кардан (санҷиш)',
  tagline: 'Омӯзиши забони русӣ',
  searchPlaceholder: 'Ҷустуҷӯи калимаҳо…',
  studiedToday: 'Имрӯз омӯхта шуда:',
  goalTitle: 'Мақсади рӯзона',
  goalDesc: 'Дар як рӯз чанд калима омӯхтан мехоҳед?',
  goalUnit: 'калима дар як рӯз',
  goalSave: 'Захира кардан',
  goalCancel: 'Бекор кардан',
  word: 'Калима',
  needLearn: 'Бояд омӯзам',
  needRepeat: 'Барои такрор',
  learned: 'Омӯхташуда',
  learnCta: 'Омӯхтани калимаҳо',
  catalogHint: 'Калимаҳои навро аз каталог илова кунед',
  aiBadge: 'AI ОМӮЗИШ',
  scenariosTitle: 'Омӯзиш тариқи суҳбат',
  seeAll: 'Ҳама →',
  scAirport: 'Дар фурудгоҳ',
  scShop: 'Дар мағоза',
  scTaxi: 'Дар таксӣ',
  trainings: 'Машқҳо',
  trainVocab: 'Машқҳои луғавӣ',
  quickTitle: 'Такрори зуд',
  quickSub: 'Калимаҳои омӯхташударо такрор кунед',
  phraseTitle: 'Ибораи рӯз',
  phraseSub: 'Ибораро омӯзед ва талаффузи худро бо ИИ санҷед',
  phraseRu: '«Добрый день, как ваши дела?»',
  phraseTj: 'Рӯз ба хайр, корҳоятон чӣ тавр?',
  accuracyEmpty: '— дақиқӣ',
  accuracyCaption: 'Баҳои миёна',
  study: 'Омӯзиш',
  nextAchievement: 'Дастоварди навбатӣ',
  achievementStatus: (cur: number, target: number) => `Пешравӣ: ${cur} / ${target}`,
  premiumTitle: 'ZabonDon Premium',
  premiumDesc: 'Ҳамаи имкониятҳоро кушоед ва бе реклама омӯзед!',
  premiumBuy: 'Харидани Premium',
  navDictionaries: 'Луғатҳо',
  navStats: 'Статистика',
  navHome: 'Асосӣ',
  navLeaderboard: 'Беҳтаринҳо',
  navProfile: 'Профил',
  exitToast: 'Барои баромад тугмаи «Назад»-ро боз як маротиба пахш кунед',
  profileTitle: 'Профил',
  guestName: 'Меҳмон',
  guestSub: 'Шумо ворид нашудаед',
  signIn: 'Ворид шудан',
  signUp: 'Сабти ном',
  authSoon: 'Воридшавӣ ба зудӣ дастрас мешавад',
  whySignIn: 'Чаро ворид шудан лозим аст?',
  benefits: [
    { icon: 'repeat', title: 'Пешравӣ дар ҳамаи дастгоҳҳо', sub: 'Калимаҳои омӯхташуда ва мақсад ҳангоми иваз кардани телефон гум намешаванд' },
    { icon: 'award', title: 'Ҷойгоҳ дар «Беҳтаринҳо»', sub: 'Бо дигар омӯзандагон мусобиқа кунед' },
    { icon: 'flame', title: 'Серия ва тангаҳо нигоҳ дошта мешаванд', sub: 'Дастовардҳои шумо ҳамеша бо шумо мемонанд' },
  ] as { icon: 'repeat' | 'award' | 'flame'; title: string; sub: string }[],
  localProgress: 'Пешравии шумо дар ин дастгоҳ',
  statStreak: 'Серия',
  statCoins: 'Тангаҳо',
  statLearned: 'Омӯхташуда',
  appVersion: 'ZabonDon · версияи 0.1',
  installTitle: 'Насб кардан ҳамчун барнома',
  installDesc: 'ZabonDon-ро ба экрани асосӣ илова кунед: он ҳамчун барномаи мобилӣ бо экрани пурра кушода мешавад.',
  installBtn: 'Насб кардан',
  installedTitle: 'Барнома насб шудааст',
  installedDesc: 'Шумо ҳоло ZabonDon-ро ҳамчун барнома истифода мебаред.',
  installIosTitle: 'Дар iPhone / iPad:',
  installIosSteps: ['Сайтро дар Safari кушоед', 'Тугмаи «Мубодила» (⬆︎)-ро пахш кунед', '«Ба экрани асосӣ» (Add to Home Screen)-ро интихоб кунед'],
  installManualTitle: 'Насби дастӣ:',
  installManualSteps: ['Менюи браузерро кушоед (⋮)', '«Насб кардани барнома» ё «Ба экрани асосӣ илова кардан»-ро интихоб кунед'],
};
