// Матнҳо аз values/strings.xml (тоҷикӣ)
export const t = {
  appName: 'ZabonDon',
  langRu: 'Русӣ',
  langTj: 'Тоҷикӣ',
  example: 'Мисол',
  finishTitle: 'Дарс анҷом ёфт!',
  finishKnown: 'Омӯхта шуд',
  mistakes: 'Хатогиҳо',
  next: 'Давом',
  know: 'Медонам',
  dontKnow: 'Омӯзиш',
  queueLabel: 'Ба омӯзиш',
  alreadyKnown: 'Медонистам',
  masteredStat: 'Аз худ шуд',
  startGames: 'Оғози бозиҳо',
  phaseIntro: 'Шиносӣ',
  phaseGames: 'Бозиҳо',
  masteredLabel: 'Аз худ шуд',
  pickTjPrompt: 'Тарҷумаро интихоб кунед',
  pickRuPrompt: 'Калимаи русиро интихоб кунед',
  typePrompt: 'Калимаро ба русӣ нависед',
  typePlaceholder: 'Ба русӣ нависед…',
  matchPrompt: 'Ҷуфтҳоро пайваст кунед',
  clozePrompt: 'Ҷойи холиро пур кунед',
  scramblePrompt: 'Калимаро аз ҳарфҳо ҷамъ кунед',
  check: 'Санҷидан',
  correct: 'Дуруст!',
  wrong: 'Нодуруст',
  rightAnswer: 'Ҷавоби дуруст:',
  roundDone: (n: number) => `${n} калима аз худ шуд!`,
  nextRound: 'Калимаҳои навбатӣ',
  finishCoins: 'Тангаҳо',
  backHome: 'Ба саҳифаи асосӣ',
  allDone: 'Ҳамаи калимаҳои намунавӣ омӯхта шуданд',
  resetProgress: 'Аз нав оғоз кардан (санҷиш)',
  tagline: 'Омӯзиши забони русӣ',
  searchPlaceholder: 'Ҷустуҷӯи калимаҳо…',
  studiedToday: 'Имрӯз омӯхта шуда:',
  word: 'Калима',
  needLearn: 'Бояд омӯзам',
  needRepeat: 'Барои такрор',
  learned: 'Омӯхташуда',
  learnCta: 'Омӯхтани калимаҳо',
  catalogHint: 'Калимаҳои навро аз каталог илова кунед',
  aiBadge: 'AI ОМӮЗИШ',
  scenariosTitle: 'Омӯзиш тариқи суҳбат',
  seeAll: 'Ҳама →',
  scAirport: 'Дар фурудгоҳ',
  scShop: 'Дар мағоза',
  scTaxi: 'Дар таксӣ',
  trainings: 'Машқҳо',
  trainVocab: 'Машқҳои луғавӣ',
  quickTitle: 'Такрори зуд',
  quickSub: 'Калимаҳои омӯхташударо такрор кунед',
  phraseTitle: 'Ибораи рӯз',
  phraseSub: 'Ибораро омӯзед ва талаффузи худро бо ИИ санҷед',
  phraseRu: '«Добрый день, как ваши дела?»',
  phraseTj: 'Рӯз ба хайр, корҳоятон чӣ тавр?',
  accuracyEmpty: '— дақиқӣ',
  accuracyCaption: 'Баҳои миёна',
  study: 'Омӯзиш',
  nextAchievement: 'Дастоварди навбатӣ',
  achievementStatus: (cur: number, target: number) => `Пешравӣ: ${cur} / ${target}`,
  premiumTitle: 'ZabonDon Premium',
  premiumDesc: 'Ҳамаи имкониятҳоро кушоед ва бе реклама омӯзед!',
  premiumBuy: 'Харидани Premium',
  navDictionaries: 'Луғатҳо',
  navStats: 'Статистика',
  navHome: 'Асосӣ',
  navLeaderboard: 'Беҳтаринҳо',
  navProfile: 'Профил',
  exitTitle: 'Баромадан аз барнома?',
  exitDesc: 'Шумо мехоҳед аз ZabonDon бароед?',
  exitHintStandalone: 'Барои баромад тугмаи «Назад»-ро боз як маротиба пахш кунед.',
  exitCancel: 'Бекор кардан',
  exitConfirm: 'Баромадан',
  exitedTitle: 'Барнома баста шуд',
  exitedDesc: 'Шумо метавонед ин саҳифаро пӯшед.',
  exitedReopen: 'Боз кардан',
  profileTitle: 'Профил',
  installTitle: 'Насб кардан ҳамчун барнома',
  installDesc: 'ZabonDon-ро ба экрани асосӣ илова кунед: он ҳамчун барномаи мобилӣ бо экрани пурра кушода мешавад.',
  installBtn: 'Насб кардан',
  installedTitle: 'Барнома насб шудааст',
  installedDesc: 'Шумо ҳоло ZabonDon-ро ҳамчун барнома истифода мебаред.',
  installIosTitle: 'Дар iPhone / iPad:',
  installIosSteps: ['Сайтро дар Safari кушоед', 'Тугмаи «Мубодила» (⬆︎)-ро пахш кунед', '«Ба экрани асосӣ» (Add to Home Screen)-ро интихоб кунед'],
  installManualTitle: 'Насби дастӣ:',
  installManualSteps: ['Менюи браузерро кушоед (⋮)', '«Насб кардани барнома» ё «Ба экрани асосӣ илова кардан»-ро интихоб кунед'],
};
