// Матнҳо аз values/strings.xml (тоҷикӣ)
export const t = {
  appName: 'ZabonDon',
  gotIt: 'Фаҳмо',
  coinRulesTitle: 'Қоидаҳои тангаҳо',
  coinRules: (reward: number, penalty: number) =>
    `• Барои ҷавоби дуруст: +${reward}\n• Барои ҷавоби нодуруст: -${penalty}\n• Формат: ҳозира / умумӣ\n• Тангаи умумӣ баъди анҷоми бозӣ нав мешавад.`,
  coinInfoTitle: 'Тангаҳо дар ZabonDon',
  coinInfoMessage:
    'Танга чист?\n\nИн суратҳисоби Шумо дар дохили барнома мебошад, ки шумо ҳангоми омӯзиши калимаҳо ба даст меоред. Онҳо барои харидори кардани версияи премиум, кушодани дигар қисмҳои барнома ва хомӯш кардани реклама пешбинӣ шудаанд.\n\nЧӣ тавр тангаҳоро ба даст овардан мумкин аст?\n\nДар бозиҳо ва машқҳо ҷавоби дуруст танга меорад, ҷавоби нодуруст аз суратҳисоби шумо тангаҳоро кам мекунад.',
  roundCoins: (n: number) => `Натиҷа: +${n} танга`,
  streakTitle: (n: number) => `${n} рӯзи фаъол`,
  streakDesc: (n: number) => `Офарин! Шумо ${n} рӯз фаъолияти бардавом доред — фардо низ омӯзед, то ба ҳадафи худ наздиктар шавед!`,
  streakGreat: 'Аъло!',
  streakBest: (n: number) => `Беҳтарин: ${n} рӯз`,
  loading: 'Бор шуда истодааст…',
  loadError: 'Пайвастшавӣ ба база ғалат шуд',
  retry: 'Аз нав кӯшиш кунед',
  levelLabel: (n: number) => `САТҲИ ${n}`,
  levelTitle: ['', 'Оғоз', 'Ҳаёти ҳаррӯза', 'Вазъиятҳои амалӣ', 'Муҳоҷират ва кор', 'Пешрафта'],
  levelSub: ['', 'Ашёи мушаххас ва дидашаванда', 'Хона, хӯрок, нақлёт ва шаҳр', 'Харид, вақт, духтур ва фурудгоҳ', 'Сарҳад, стройка ва касбҳо', 'Калимаҳои абстрактӣ ва нодир'],
  wordsCount: (n: number) => `${n} калима`,
  premiumLocked: 'Ин категория барои Premium аст',
  premiumLockedSub: 'Бо Premium ҳамаи категорияҳо кушода мешаванд',
  notFound: 'Чизе ёфт нашуд',
  searchWords: 'Ҷустуҷӯи калима ё категория…',
  catalog: 'Каталог',
  noWords: 'Дар ин категория калима нест',
  statusKnown: 'Омӯхта шуд',
  statusRepeat: 'Дар омӯзиш',
  langRu: 'Русӣ',
  langTj: 'Тоҷикӣ',
  example: 'Мисол',
  finishTitle: 'Дарс анҷом ёфт!',
  finishKnown: 'Омӯхта шуд',
  mistakes: 'Хатогиҳо',
  next: 'Давом',
  know: 'Медонам',
  dontKnow: 'Омӯзиш',
  queueLabel: 'Ба омӯзиш',
  alreadyKnown: 'Медонистам',
  masteredStat: 'Аз худ шуд',
  startGames: 'Оғози бозиҳо',
  phaseIntro: 'Шиносӣ',
  phaseGames: 'Бозиҳо',
  masteredLabel: 'Аз худ шуд',
  pickTjPrompt: 'Тарҷумаро интихоб кунед',
  pickRuPrompt: 'Калимаи русиро интихоб кунед',
  typePrompt: 'Калимаро ба русӣ нависед',
  typePlaceholder: 'Ба русӣ нависед…',
  matchPrompt: 'Ҷуфтҳоро пайваст кунед',
  clozePrompt: 'Ҷойи холиро пур кунед',
  scramblePrompt: 'Калимаро аз ҳарфҳо ҷамъ кунед',
  check: 'Санҷидан',
  correct: 'Дуруст!',
  wrong: 'Нодуруст',
  rightAnswer: 'Ҷавоби дуруст:',
  roundDone: (n: number) => `${n} калима аз худ шуд!`,
  nextRound: 'Калимаҳои навбатӣ',
  finishCoins: 'Тангаҳо',
  backHome: 'Ба саҳифаи асосӣ',
  allDone: 'Ҳамаи калимаҳои намунавӣ омӯхта шуданд',
  resetProgress: 'Аз нав оғоз кардан (санҷиш)',
  tagline: 'Омӯзиши забони русӣ',
  searchPlaceholder: 'Ҷустуҷӯи калимаҳо…',
  searchClear: 'Пок кардани матн',
  searchClose: 'Пӯшидани ҷустуҷӯ',
  searchHint: 'Калима ё категорияро ба русӣ ё тоҷикӣ нависед',
  searchSectionCategories: 'Категорияҳо',
  searchSectionWords: 'Калимаҳо',
  studiedToday: 'Имрӯз омӯхта шуда:',
  goalTitle: 'Мақсади рӯзона',
  goalDesc: 'Дар як рӯз чанд калима омӯхтан мехоҳед?',
  goalUnit: 'калима дар як рӯз',
  goalSave: 'Захира кардан',
  goalCancel: 'Бекор кардан',
  word: 'Калима',
  needLearn: 'Бояд омӯзам',
  needRepeat: 'Барои такрор',
  learned: 'Омӯхташуда',
  learnCta: 'Омӯхтани калимаҳо',
  catalogHint: 'Калимаҳои навро аз каталог илова кунед',
  aiBadge: 'AI ОМӮЗИШ',
  scenariosTitle: 'Омӯзиш тариқи суҳбат',
  seeAll: 'Ҳама →',
  scAirport: 'Дар фурудгоҳ',
  scShop: 'Дар мағоза',
  scTaxi: 'Дар таксӣ',
  trainings: 'Машқҳо',
  trainVocab: 'Машқҳои луғавӣ',
  quickTitle: 'Такрори зуд',
  quickSub: 'Калимаҳои омӯхташударо такрор кунед',
  phraseTitle: 'Ибораи рӯз',
  phraseSub: 'Ибораро омӯзед ва талаффузи худро бо ИИ санҷед',
  phraseRu: '«Добрый день, как ваши дела?»',
  phraseTj: 'Рӯз ба хайр, корҳоятон чӣ тавр?',
  accuracyEmpty: '— дақиқӣ',
  accuracyCaption: 'Баҳои миёна',
  study: 'Омӯзиш',
  nextAchievement: 'Дастоварди навбатӣ',
  achievementStatus: (cur: number, target: number) => `Пешравӣ: ${cur} / ${target}`,
  premiumTitle: 'ZabonDon Premium',
  premiumDesc: 'Ҳамаи имкониятҳоро кушоед ва бе реклама омӯзед!',
  premiumBuy: 'Харидани Premium',
  navDictionaries: 'Луғатҳо',
  navStats: 'Статистика',
  navHome: 'Асосӣ',
  navLeaderboard: 'Беҳтаринҳо',
  navProfile: 'Профил',
  exitToast: 'Барои баромад тугмаи «Назад»-ро боз як маротиба пахш кунед',
  profileTitle: 'Профил',
  guestName: 'Меҳмон',
  guestSub: 'Шумо ворид нашудаед',
  signIn: 'Ворид шудан',
  signUp: 'Сабти ном',
  whySignIn: 'Чаро ворид шудан лозим аст?',
  benefits: [
    { icon: 'repeat', title: 'Пешравӣ дар ҳамаи дастгоҳҳо', sub: 'Калимаҳои омӯхташуда ва мақсад ҳангоми иваз кардани телефон гум намешаванд' },
    { icon: 'award', title: 'Ҷойгоҳ дар «Беҳтаринҳо»', sub: 'Бо дигар омӯзандагон мусобиқа кунед' },
    { icon: 'flame', title: 'Серия ва тангаҳо нигоҳ дошта мешаванд', sub: 'Дастовардҳои шумо ҳамеша бо шумо мемонанд' },
  ] as { icon: 'repeat' | 'award' | 'flame'; title: string; sub: string }[],
  authSignInTitle: 'Воридшавӣ',
  authSignUpTitle: 'Сабти ном',
  authSignInSub: 'Бо почтаи электронӣ ворид шавед',
  authSignUpSub: 'Ҳисоби нав созед, то пешравии шумо нигоҳ дошта шавад',
  fieldName: 'Ном',
  fieldNamePh: 'Номи шумо',
  fieldEmail: 'Почтаи электронӣ',
  fieldEmailPh: 'name@example.com',
  fieldPassword: 'Парол',
  fieldPasswordPh: 'Ҳадди ақал 6 аломат',
  fieldConfirm: 'Паролро такрор кунед',
  showPassword: 'Нишон додан',
  hidePassword: 'Пинҳон кардан',
  forgotPassword: 'Паролро фаромӯш кардед?',
  noAccount: 'Ҳисоб надоред?',
  haveAccount: 'Ҳисоб доред?',
  resetTitle: 'Барқарор кардани парол',
  resetSub: 'Почтаи худро нависед, мо истинод барои парол иваз кардан мефиристем',
  resetSend: 'Фиристодани истинод',
  resetSent: 'Нома фиристода шуд. Почтаи худро (ва «Спам»-ро) тафтиш кунед.',
  backToSignIn: 'Бозгашт ба воридшавӣ',
  errName: 'Номро нависед (ҳадди ақал 2 ҳарф)',
  errEmail: 'Почтаи электрониро дуруст нависед',
  errPassword: 'Парол бояд ҳадди ақал 6 аломат бошад',
  errConfirm: 'Паролҳо мувофиқат намекунанд',
  authErrNotConfigured: 'Воридшавӣ ҳоло танзим нашудааст. Баъдтар кӯшиш кунед.',
  authErrNetwork: 'Пайвастшавӣ ба интернет нест. Санҷед ва аз нав кӯшиш кунед.',
  authErrEmailExists: 'Бо ин почта ҳисоб аллакай ҳаст. Ворид шавед.',
  authErrInvalidEmail: 'Почтаи электронӣ нодуруст аст.',
  authErrWeakPassword: 'Парол хеле суст аст. Ҳадди ақал 6 аломат.',
  authErrCredentials: 'Почта ё парол нодуруст аст.',
  authErrDisabled: 'Ин ҳисоб баста шудааст.',
  authErrTooMany: 'Кӯшишҳо хеле зиёданд. Каме интизор шавед ва аз нав кӯшиш кунед.',
  authErrNotAllowed: 'Воридшавӣ бо почта дар барнома фаъол нест.',
  authErrUnknown: 'Хатои номаълум. Аз нав кӯшиш кунед.',
  authNotConfiguredBanner: 'Воридшавӣ ҳоло ба база пайваст нашудааст (калиди Firebase дода нашудааст).',
  signedInAs: 'Шумо ворид шудед',
  signOut: 'Баромадан аз ҳисоб',
  localProgress: 'Пешравии шумо дар ин дастгоҳ',
  statStreak: 'Серия',
  statCoins: 'Тангаҳо',
  statLearned: 'Омӯхташуда',
  appVersion: 'ZabonDon · версияи 0.1',
  installTitle: 'Насб кардан ҳамчун барнома',
  installDesc: 'ZabonDon-ро ба экрани асосӣ илова кунед: он ҳамчун барномаи мобилӣ бо экрани пурра кушода мешавад.',
  installBtn: 'Насб кардан',
  installedTitle: 'Барнома насб шудааст',
  installedDesc: 'Шумо ҳоло ZabonDon-ро ҳамчун барнома истифода мебаред.',
  installIosTitle: 'Дар iPhone / iPad:',
  installIosSteps: ['Сайтро дар Safari кушоед', 'Тугмаи «Мубодила» (⬆︎)-ро пахш кунед', '«Ба экрани асосӣ» (Add to Home Screen)-ро интихоб кунед'],
  installManualTitle: 'Насби дастӣ:',
  installManualSteps: ['Менюи браузерро кушоед (⋮)', '«Насб кардани барнома» ё «Ба экрани асосӣ илова кардан»-ро интихоб кунед'],
};
